export const IPO_DATA = [
  {
    id: "1",
    name: "GO AIR",
    date: "4th - 7th Oct 2022",
    size: "₹3,600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    sharesLots: "100 Shares/5 Lots",
    logo: "/images/goair.jpg",
    issueSize: "₹3,600 - 3,700 Cr.",
    priceRangeDetail: "₹50 - 60",
    minAmount: "₹50,000",
    lotSize: "100 shares/lots",
    issueDates: "4th Oct - 7th Oct 2022",
    listedOn: "15 Dec 22",
    listedPrice: "₹150",
    listingGains: "₹10 (10%)",
    timeline: [
      { stage: "Bidding starts", date: "12 Dec 2023" },
      { stage: "Bidding ends", date: "15 Dec 2023" },
      { stage: "Allotment finalization", date: "18 Dec 2023" },
      { stage: "Refund initiation", date: "18 Dec 2023" },
      { stage: "Demat transfer", date: "18 Dec 2023" },
      { stage: "Listing date", date: "21 Dec 2023" },
    ],
    about:
      "GO AIR is a budget airline focused on providing low-cost air travel within India. The company aims to expand its fleet and increase destinations, making air travel affordable for all.",
  },
  {
    id: "2",
    name: "BAJAJ ENERGY",
    date: "4th - 7th Oct 2022",
    size: "₹3,600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    sharesLots: "100 Shares/5 Lots",
    logo: "/images/bajaj.png",
    issueSize: "₹3,600 - 3,700 Cr.",
    priceRangeDetail: "₹50 - 60",
    minAmount: "₹50,000",
    lotSize: "100 shares/lots",
    issueDates: "4th Oct - 7th Oct 2022",
    listedOn: "15 Dec 22",
    listedPrice: "₹150",
    listingGains: "₹10 (10%)",
    timeline: [
      { stage: "Bidding starts", date: "12 Dec 2023" },
      { stage: "Bidding ends", date: "15 Dec 2023" },
      { stage: "Allotment finalization", date: "18 Dec 2023" },
      { stage: "Refund initiation", date: "18 Dec 2023" },
      { stage: "Demat transfer", date: "18 Dec 2023" },
      { stage: "Listing date", date: "21 Dec 2023" },
    ],
    about:
      "Bajaj Energy is one of India’s largest thermal power generation companies. It provides a significant share of electricity to northern India and is focusing on eco-friendly upgrades.",
  },
  {
    id: "3",
    name: "OYO",
    date: "To be announced",
    size: "₹3,600 Crores",
    priceRange: "₹50-60",
    minInvestment: "₹50,000",
    sharesLots: "100 Shares/5 Lots",
    logo: "/images/oyo.png",
    issueSize: "₹3,600 - 3,700 Cr.",
    priceRangeDetail: "₹50 - 60",
    minAmount: "₹50,000",
    lotSize: "100 shares/lots",
    issueDates: "12 Dec - 15 Dec 2023",
    listedOn: "15 Dec 23",
    listedPrice: "₹150",
    listingGains: "₹10 (10%)",
    timeline: [
      { stage: "Bidding starts", date: "12 Dec 2023" },
      { stage: "Bidding ends", date: "15 Dec 2023" },
      { stage: "Allotment finalization", date: "18 Dec 2023" },
      { stage: "Refund initiation", date: "18 Dec 2023" },
      { stage: "Demat transfer", date: "18 Dec 2023" },
      { stage: "Listing date", date: "21 Dec 2023" },
    ],
    about:
      "OYO is a leading hospitality chain, offering affordable and reliable accommodations worldwide. The company is expanding its digital services and focusing on enhanced user experience.",
  },
];
